use_frameworks!

platform :ios, '9.0'

target 'TTImagePickerManager_Example' do
  pod 'TTImagePickerManager', :path => '../'
  pod 'Masonry'
  target 'TTImagePickerManager_Tests' do
    inherit! :search_paths

    
  end
end
