use_frameworks!

platform :ios, '8.0'

target 'TTImagePickerManager_Example' do
  pod 'TTImagePickerManager', :path => '../'

  target 'TTImagePickerManager_Tests' do
    inherit! :search_paths

    
  end
end
